{{- if .Values.preJob.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - cp -rf /var/choerodon/* /tools
        image: {{ .Values.preJob.image }}
        imagePullPolicy: Always
        name: tools
        volumeMounts:
        - mountPath: /tools
          name: tools-jar
      containers:
      - name: {{ .Release.Name }}-init-db
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - 'java -Xms256M -Xmx512M -Dspring.datasource.url=jdbc:mysql://{{ .Values.env.open.MYSQL_HOST }}:{{ .Values.env.open.MYSQL_PORT }}/{{ .Values.env.open.MYSQL_DB }}  -Dspring.datasource.username={{ .Values.env.open.MYSQL_USER }} -Dspring.datasource.password={{ .Values.env.open.MYSQL_PASS }} -Dmetadata.init=false -Ddata.mode=all -Ddata.jar=hap.jar -jar /var/choerodon/choerodon-tool-liquibase.jar'
        volumeMounts:
        - mountPath: /var/choerodon
          name: tools-jar
      volumes:
      - emptyDir: {}
        name: tools-jar
      restartPolicy: Never
{{- end }}